#Server configuration
BMGR_DB_USER="bmgr_user"
BMGR_DB_PASS="bmgr_pass"
BMGR_DB_HOST="localhost"
BMGR_TEMPLATE_PATH="/etc/bmgr/templates/"

#Client configuration
BMGR_CLIENT_URL="http://localhost/bmgr"

# init data
BMGR_INIT_DATA = [
    {"type": "resource", "name": "ipxe_normal_boot", "template_uri": "file://disk_boot.ipxe.jinja"},
    {"type": "resource", "name": "ipxe_deploy_boot", "template_uri": "file://deploy_boot.ipxe.jinja"},
    {"type": "resource", "name": "kickstart", "template_uri": "file://ks_rhel7.jinja"},
    {"type": "resource", "name": "poap_config", "template_uri": "file://poap_config.jinja"},
    {"type": "alias", "name": "ipxe_boot", "target": "ipxe_normal_boot"}
]

# Jinja2 customs filters and globals
BMGR_JINJA_CUSTOMS_PACKAGE_PATH="bmgr/customs"

# Enable recursive rendering
BMGR_ENABLE_RECURSIVE_RENDERING=True

